"""empty message

Revision ID: 32e4b1ec1a75
Revises: 
Create Date: 2018-03-08 18:48:00.395862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e4b1ec1a75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('modules', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('module',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('sets', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('module_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('account',
    sa.Column('account_index', sa.Integer(), nullable=False),
    sa.Column('fk_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_account_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('account_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('module')
    op.drop_table('course')
    # ### end Alembic commands ###
