"""empty message

Revision ID: 68fc0e9ec58f
Revises: 32e4b1ec1a75
Create Date: 2018-03-08 22:54:27.069243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68fc0e9ec58f'
down_revision = '32e4b1ec1a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('modules', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('modules',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('sets', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('module_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('resource_link', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('quiz_link', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_table('accounts',
    sa.Column('account_index', sa.Integer(), nullable=False),
    sa.Column('fk_account_id', sa.Integer(), nullable=True),
    sa.Column('fk_account_role', sa.Integer(), nullable=True),
    sa.Column('courses', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['fk_account_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['fk_account_role'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('account_index')
    )
    op.drop_index('title', table_name='module')
    op.drop_table('module')
    op.drop_index('title', table_name='course')
    op.drop_table('course')
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_index', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fk_account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_account_id'], ['users.user_id'], name='account_ibfk_1'),
    sa.PrimaryKeyConstraint('account_index'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('course_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('modules', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'course', ['title'], unique=True)
    op.create_table('module',
    sa.Column('module_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('sets', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('module_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'module', ['title'], unique=True)
    op.drop_table('accounts')
    op.drop_table('sets')
    op.drop_table('roles')
    op.drop_table('modules')
    op.drop_table('courses')
    # ### end Alembic commands ###
