"""empty message

Revision ID: aaa55a14f7f4
Revises: 
Create Date: 2018-03-09 08:51:53.516581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaa55a14f7f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('modules', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('modules',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('sets', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('module_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('resource_link', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('quiz_link', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_table('accounts',
    sa.Column('account_index', sa.Integer(), nullable=False),
    sa.Column('fk_account_id', sa.Integer(), nullable=True),
    sa.Column('fk_account_role', sa.Integer(), nullable=True),
    sa.Column('courses', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['fk_account_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['fk_account_role'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('account_index')
    )
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_index', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.user_id'], name='account_ibfk_1'),
    sa.PrimaryKeyConstraint('account_index'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('accounts')
    op.drop_table('sets')
    op.drop_table('roles')
    op.drop_table('modules')
    op.drop_table('courses')
    # ### end Alembic commands ###
